### PR TITLE
fix: Remove PHP 8.0 syntax to maintain PHP 7.4 compatibility

### PR DESCRIPTION
**Pull request by oatmael**
Union return types are not supported in PHP 7.4. Thankfully, `T|null` is equivalent to `?T`. See below:
https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.nullable

### CODE REVIEW

**Review by mhmd-azeez — APPROVED** [review]
Looks great, thanks! the CI is failing because of an unrelated issue. I have fixed the issue in #20. Will merge this PR once #20 is merged

**Comment by mhmd-azeez** [comment]
Now that #20 is merged, @oatmael can you please rebase/merge the changes into your branch?

**Comment by oatmael** [comment]
> Now that #20 is merged, @oatmael can you please rebase/merge the changes into your branch?

Done 👍

**Comment by oatmael** [comment]
@mhmd-azeez poking on this - looks like the CI failed from a rate limit 😅

**Comment by mhmd-azeez** [comment]
Thanks a bunch, great work!

**Pull request merged**
